"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ApiController;
(function (ApiController) {
    ApiController["Dropdown"] = "Dropdown";
    ApiController["Product"] = "Product";
    ApiController["ProductPackage"] = "ProductPackage";
    ApiController["ProductCategory"] = "ProductCategory";
    ApiController["Impersonation"] = "Impersonation";
    ApiController["CustomerApplication"] = "CustomerApplication";
    ApiController["CompletedApplication"] = "CompletedApplication";
    ApiController["Registration"] = "Registration";
    ApiController["AdminUser"] = "AdminUser";
    ApiController["Agent"] = "Agent";
    ApiController["User"] = "User";
    ApiController["AgentPocket"] = "AgentPocket";
    ApiController["Commission"] = "Commission";
    ApiController["Dashboard"] = "Dashboard";
    ApiController["Download"] = "Download";
    ApiController["Announcement"] = "Announcement";
    ApiController["Communication"] = "Communication";
    ApiController["WithdrawalView"] = "WithdrawalView";
    ApiController["WithdrawalSubmit"] = "WithdrawalSubmit";
    ApiController["Clawback"] = "Clawback";
    ApiController["Incentives"] = "Incentives";
    ApiController["IncentivesUpload"] = "IncentivesUpload";
    ApiController["LoginBanner"] = "LoginBanner";
    ApiController["Password"] = "Password";
    ApiController["ReportAgentSubmission"] = "ReportAgentSubmission";
    ApiController["ReportAgentWithdrawal"] = "ReportAgentWithdrawal";
})(ApiController = exports.ApiController || (exports.ApiController = {}));
//# sourceMappingURL=apiController.js.map