//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentCommission
    {
        public int CommId { get; set; }
        public int AgentId { get; set; }
        public int CategoryId { get; set; }
        public short AgentCommission1 { get; set; }
        public short SuperiorCommission { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Agent Agent { get; set; }
    }
}
