//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentCharge
    {
        public int ChargeId { get; set; }
        public string Agent { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> WithdrawalId { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Withdrawal Withdrawal { get; set; }
    }
}
