//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentCommissions = new HashSet<AgentCommission>();
        }
    
        public int AgentId { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Nric { get; set; }
        public string CompanyName { get; set; }
        public string CompanyRegNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string MobileNo { get; set; }
        public string TelNo { get; set; }
        public string BankName { get; set; }
        public string BankAccNo { get; set; }
        public string UserLogin { get; set; }
        public byte[] PasswordHash { get; set; }
        public Nullable<int> SuperiorId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentCommission> AgentCommissions { get; set; }
    }
}
