//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BroadbandZoneEntities : DbContext
    {
        public BroadbandZoneEntities()
            : base("name=BroadbandZoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AgentCommission> AgentCommissions { get; set; }
        public virtual DbSet<DropdownItem> DropdownItems { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductPackage> ProductPackages { get; set; }
        public virtual DbSet<CustomerDocument> CustomerDocuments { get; set; }
        public virtual DbSet<AnnouncementDocument> AnnouncementDocuments { get; set; }
        public virtual DbSet<ClaimableCommission> ClaimableCommissions { get; set; }
        public virtual DbSet<Clawback> Clawbacks { get; set; }
        public virtual DbSet<IncentiveReceived> IncentiveReceiveds { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<LoginPageBanner> LoginPageBanners { get; set; }
        public virtual DbSet<LoginTrail> LoginTrails { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<CustomerApplication> CustomerApplications { get; set; }
        public virtual DbSet<RegistrationDocument> RegistrationDocuments { get; set; }
        public virtual DbSet<SProcErrorLog> SProcErrorLogs { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<ApplicationStatu> ApplicationStatus { get; set; }
        public virtual DbSet<AgentPocket> AgentPockets { get; set; }
        public virtual DbSet<Withdrawal> Withdrawals { get; set; }
        public virtual DbSet<WithdrawalItem> WithdrawalItems { get; set; }
    
        public virtual ObjectResult<GetProductCategory_Result> GetProductCategory(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, Nullable<bool> prRecordStatus, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prRecordStatusParameter = prRecordStatus.HasValue ?
                new ObjectParameter("prRecordStatus", prRecordStatus) :
                new ObjectParameter("prRecordStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductCategory_Result>("GetProductCategory", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prRecordStatusParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<GetProductPackages_Result> GetProductPackages(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, Nullable<bool> prRecordStatus, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prRecordStatusParameter = prRecordStatus.HasValue ?
                new ObjectParameter("prRecordStatus", prRecordStatus) :
                new ObjectParameter("prRecordStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductPackages_Result>("GetProductPackages", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prRecordStatusParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<GetProducts_Result> GetProducts(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, Nullable<bool> prRecordStatus, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prRecordStatusParameter = prRecordStatus.HasValue ?
                new ObjectParameter("prRecordStatus", prRecordStatus) :
                new ObjectParameter("prRecordStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prRecordStatusParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<GetCustomerApplication_Result> GetCustomerApplication(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, Nullable<int> prProduct, Nullable<int> prProductCategory, Nullable<int> prProductPackage, Nullable<int> prStatus, string prAgent, Nullable<System.DateTime> prSubmittedFrom, Nullable<System.DateTime> prSubmittedTo, Nullable<System.DateTime> prActivatedFrom, Nullable<System.DateTime> prActivatedTo, string prResidentialType, string prKeyword, Nullable<bool> prDocumentCompleted, Nullable<bool> prIsAdmin, Nullable<int> prAgentId, Nullable<int> prFilterMode, ObjectParameter oTotalRecord, ObjectParameter oTotalUnreadMsg, ObjectParameter oTotalCommINotConfig, ObjectParameter oTotalOddClaimed)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prProductParameter = prProduct.HasValue ?
                new ObjectParameter("prProduct", prProduct) :
                new ObjectParameter("prProduct", typeof(int));
    
            var prProductCategoryParameter = prProductCategory.HasValue ?
                new ObjectParameter("prProductCategory", prProductCategory) :
                new ObjectParameter("prProductCategory", typeof(int));
    
            var prProductPackageParameter = prProductPackage.HasValue ?
                new ObjectParameter("prProductPackage", prProductPackage) :
                new ObjectParameter("prProductPackage", typeof(int));
    
            var prStatusParameter = prStatus.HasValue ?
                new ObjectParameter("prStatus", prStatus) :
                new ObjectParameter("prStatus", typeof(int));
    
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            var prSubmittedFromParameter = prSubmittedFrom.HasValue ?
                new ObjectParameter("prSubmittedFrom", prSubmittedFrom) :
                new ObjectParameter("prSubmittedFrom", typeof(System.DateTime));
    
            var prSubmittedToParameter = prSubmittedTo.HasValue ?
                new ObjectParameter("prSubmittedTo", prSubmittedTo) :
                new ObjectParameter("prSubmittedTo", typeof(System.DateTime));
    
            var prActivatedFromParameter = prActivatedFrom.HasValue ?
                new ObjectParameter("prActivatedFrom", prActivatedFrom) :
                new ObjectParameter("prActivatedFrom", typeof(System.DateTime));
    
            var prActivatedToParameter = prActivatedTo.HasValue ?
                new ObjectParameter("prActivatedTo", prActivatedTo) :
                new ObjectParameter("prActivatedTo", typeof(System.DateTime));
    
            var prResidentialTypeParameter = prResidentialType != null ?
                new ObjectParameter("prResidentialType", prResidentialType) :
                new ObjectParameter("prResidentialType", typeof(string));
    
            var prKeywordParameter = prKeyword != null ?
                new ObjectParameter("prKeyword", prKeyword) :
                new ObjectParameter("prKeyword", typeof(string));
    
            var prDocumentCompletedParameter = prDocumentCompleted.HasValue ?
                new ObjectParameter("prDocumentCompleted", prDocumentCompleted) :
                new ObjectParameter("prDocumentCompleted", typeof(bool));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            var prFilterModeParameter = prFilterMode.HasValue ?
                new ObjectParameter("prFilterMode", prFilterMode) :
                new ObjectParameter("prFilterMode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerApplication_Result>("GetCustomerApplication", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prProductParameter, prProductCategoryParameter, prProductPackageParameter, prStatusParameter, prAgentParameter, prSubmittedFromParameter, prSubmittedToParameter, prActivatedFromParameter, prActivatedToParameter, prResidentialTypeParameter, prKeywordParameter, prDocumentCompletedParameter, prIsAdminParameter, prAgentIdParameter, prFilterModeParameter, oTotalRecord, oTotalUnreadMsg, oTotalCommINotConfig, oTotalOddClaimed);
        }
    
        public virtual ObjectResult<GetDropdownItems_Result> GetDropdownItems(string prFieldName)
        {
            var prFieldNameParameter = prFieldName != null ?
                new ObjectParameter("prFieldName", prFieldName) :
                new ObjectParameter("prFieldName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDropdownItems_Result>("GetDropdownItems", prFieldNameParameter);
        }
    
        public virtual ObjectResult<byte[]> GenerateEncryptedPwd(string prUserLogin)
        {
            var prUserLoginParameter = prUserLogin != null ?
                new ObjectParameter("prUserLogin", prUserLogin) :
                new ObjectParameter("prUserLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("GenerateEncryptedPwd", prUserLoginParameter);
        }
    
        public virtual ObjectResult<AuthenticatedUser> AuthenticateUser(string prLogin, string prPassword, Nullable<bool> prIsAdmin, Nullable<bool> prImpersonate)
        {
            var prLoginParameter = prLogin != null ?
                new ObjectParameter("prLogin", prLogin) :
                new ObjectParameter("prLogin", typeof(string));
    
            var prPasswordParameter = prPassword != null ?
                new ObjectParameter("prPassword", prPassword) :
                new ObjectParameter("prPassword", typeof(string));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            var prImpersonateParameter = prImpersonate.HasValue ?
                new ObjectParameter("prImpersonate", prImpersonate) :
                new ObjectParameter("prImpersonate", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthenticatedUser>("AuthenticateUser", prLoginParameter, prPasswordParameter, prIsAdminParameter, prImpersonateParameter);
        }
    
        public virtual ObjectResult<GetAgentRegistration_Result> GetAgentRegistration(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, Nullable<int> prRecordStatus, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prRecordStatusParameter = prRecordStatus.HasValue ?
                new ObjectParameter("prRecordStatus", prRecordStatus) :
                new ObjectParameter("prRecordStatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentRegistration_Result>("GetAgentRegistration", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prRecordStatusParameter, oTotalRecord);
        }
    
        public virtual int SendActivationCode(Nullable<int> prRegistrationId, string prEmail)
        {
            var prRegistrationIdParameter = prRegistrationId.HasValue ?
                new ObjectParameter("prRegistrationId", prRegistrationId) :
                new ObjectParameter("prRegistrationId", typeof(int));
    
            var prEmailParameter = prEmail != null ?
                new ObjectParameter("prEmail", prEmail) :
                new ObjectParameter("prEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SendActivationCode", prRegistrationIdParameter, prEmailParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> ActivateAgent(string prActivationCode)
        {
            var prActivationCodeParameter = prActivationCode != null ?
                new ObjectParameter("prActivationCode", prActivationCode) :
                new ObjectParameter("prActivationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("ActivateAgent", prActivationCodeParameter);
        }
    
        public virtual ObjectResult<GetAgentProfile_Result> GetAgentProfile(string prUsername, Nullable<int> prAgentId)
        {
            var prUsernameParameter = prUsername != null ?
                new ObjectParameter("prUsername", prUsername) :
                new ObjectParameter("prUsername", typeof(string));
    
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentProfile_Result>("GetAgentProfile", prUsernameParameter, prAgentIdParameter);
        }
    
        public virtual ObjectResult<GetRegistrationDetails_Result> GetRegistrationDetails(Nullable<int> prRegId)
        {
            var prRegIdParameter = prRegId.HasValue ?
                new ObjectParameter("prRegId", prRegId) :
                new ObjectParameter("prRegId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRegistrationDetails_Result>("GetRegistrationDetails", prRegIdParameter);
        }
    
        public virtual ObjectResult<GetAgents_Result> GetAgents(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, Nullable<bool> prRecordStatus, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prRecordStatusParameter = prRecordStatus.HasValue ?
                new ObjectParameter("prRecordStatus", prRecordStatus) :
                new ObjectParameter("prRecordStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgents_Result>("GetAgents", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prRecordStatusParameter, oTotalRecord);
        }
    
        public virtual int InsertCommissionSettings(string prAgents, string prCreatedBy)
        {
            var prAgentsParameter = prAgents != null ?
                new ObjectParameter("prAgents", prAgents) :
                new ObjectParameter("prAgents", typeof(string));
    
            var prCreatedByParameter = prCreatedBy != null ?
                new ObjectParameter("prCreatedBy", prCreatedBy) :
                new ObjectParameter("prCreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCommissionSettings", prAgentsParameter, prCreatedByParameter);
        }
    
        public virtual ObjectResult<CommissionSettings> GetCommissionSettings(Nullable<int> prProductId, string prAgentAcc)
        {
            var prProductIdParameter = prProductId.HasValue ?
                new ObjectParameter("prProductId", prProductId) :
                new ObjectParameter("prProductId", typeof(int));
    
            var prAgentAccParameter = prAgentAcc != null ?
                new ObjectParameter("prAgentAcc", prAgentAcc) :
                new ObjectParameter("prAgentAcc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CommissionSettings>("GetCommissionSettings", prProductIdParameter, prAgentAccParameter);
        }
    
        public virtual ObjectResult<GetAgentCommissionSettings_Result1> GetAgentCommissionSettings(Nullable<int> prAgentId, Nullable<int> prProductId)
        {
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            var prProductIdParameter = prProductId.HasValue ?
                new ObjectParameter("prProductId", prProductId) :
                new ObjectParameter("prProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentCommissionSettings_Result1>("GetAgentCommissionSettings", prAgentIdParameter, prProductIdParameter);
        }
    
        public virtual ObjectResult<DashboardMyTeamSubmissions_Result> DashboardMyTeamSubmissions(Nullable<int> prSuperiorId, ObjectParameter oTotalAllAgents)
        {
            var prSuperiorIdParameter = prSuperiorId.HasValue ?
                new ObjectParameter("prSuperiorId", prSuperiorId) :
                new ObjectParameter("prSuperiorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardMyTeamSubmissions_Result>("DashboardMyTeamSubmissions", prSuperiorIdParameter, oTotalAllAgents);
        }
    
        public virtual ObjectResult<GetAnnouncement_Result> GetAnnouncement(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prTitle, Nullable<bool> prIsActive, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prTitleParameter = prTitle != null ?
                new ObjectParameter("prTitle", prTitle) :
                new ObjectParameter("prTitle", typeof(string));
    
            var prIsActiveParameter = prIsActive.HasValue ?
                new ObjectParameter("prIsActive", prIsActive) :
                new ObjectParameter("prIsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAnnouncement_Result>("GetAnnouncement", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prTitleParameter, prIsActiveParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<DboardSubmissionStatusCount_Result> DboardSubmissionStatusCount(Nullable<int> prSuperiorId, Nullable<int> prYear)
        {
            var prSuperiorIdParameter = prSuperiorId.HasValue ?
                new ObjectParameter("prSuperiorId", prSuperiorId) :
                new ObjectParameter("prSuperiorId", typeof(int));
    
            var prYearParameter = prYear.HasValue ?
                new ObjectParameter("prYear", prYear) :
                new ObjectParameter("prYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DboardSubmissionStatusCount_Result>("DboardSubmissionStatusCount", prSuperiorIdParameter, prYearParameter);
        }
    
        public virtual ObjectResult<GetWithdrawalSubmitted_Result> GetWithdrawalSubmitted(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prStatus, string prAgent, Nullable<System.DateTime> prSubmittedFrom, Nullable<System.DateTime> prSubmittedTo, Nullable<System.DateTime> prCompletedFrom, Nullable<System.DateTime> prCompletedTo, ObjectParameter oTotalRecord, ObjectParameter oTotalAmountClaimed, ObjectParameter oTotalAmountPayout)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prStatusParameter = prStatus != null ?
                new ObjectParameter("prStatus", prStatus) :
                new ObjectParameter("prStatus", typeof(string));
    
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            var prSubmittedFromParameter = prSubmittedFrom.HasValue ?
                new ObjectParameter("prSubmittedFrom", prSubmittedFrom) :
                new ObjectParameter("prSubmittedFrom", typeof(System.DateTime));
    
            var prSubmittedToParameter = prSubmittedTo.HasValue ?
                new ObjectParameter("prSubmittedTo", prSubmittedTo) :
                new ObjectParameter("prSubmittedTo", typeof(System.DateTime));
    
            var prCompletedFromParameter = prCompletedFrom.HasValue ?
                new ObjectParameter("prCompletedFrom", prCompletedFrom) :
                new ObjectParameter("prCompletedFrom", typeof(System.DateTime));
    
            var prCompletedToParameter = prCompletedTo.HasValue ?
                new ObjectParameter("prCompletedTo", prCompletedTo) :
                new ObjectParameter("prCompletedTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWithdrawalSubmitted_Result>("GetWithdrawalSubmitted", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prStatusParameter, prAgentParameter, prSubmittedFromParameter, prSubmittedToParameter, prCompletedFromParameter, prCompletedToParameter, oTotalRecord, oTotalAmountClaimed, oTotalAmountPayout);
        }
    
        public virtual ObjectResult<GetWithdrawalToSubmit_Result> GetWithdrawalToSubmit(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prAgent, string prSearchKeyword, Nullable<System.DateTime> prSubmittedFrom, Nullable<System.DateTime> prSubmittedTo, ObjectParameter oTotalRecord, ObjectParameter oTotalIncentives, ObjectParameter oTotalDeduction)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prSubmittedFromParameter = prSubmittedFrom.HasValue ?
                new ObjectParameter("prSubmittedFrom", prSubmittedFrom) :
                new ObjectParameter("prSubmittedFrom", typeof(System.DateTime));
    
            var prSubmittedToParameter = prSubmittedTo.HasValue ?
                new ObjectParameter("prSubmittedTo", prSubmittedTo) :
                new ObjectParameter("prSubmittedTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWithdrawalToSubmit_Result>("GetWithdrawalToSubmit", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prAgentParameter, prSearchKeywordParameter, prSubmittedFromParameter, prSubmittedToParameter, oTotalRecord, oTotalIncentives, oTotalDeduction);
        }
    
        public virtual ObjectResult<GetWithdrawalItems_Result> GetWithdrawalItems(Nullable<int> prWithdrawalId)
        {
            var prWithdrawalIdParameter = prWithdrawalId.HasValue ?
                new ObjectParameter("prWithdrawalId", prWithdrawalId) :
                new ObjectParameter("prWithdrawalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWithdrawalItems_Result>("GetWithdrawalItems", prWithdrawalIdParameter);
        }
    
        public virtual ObjectResult<GetPaymentDetails_Result> GetPaymentDetails(Nullable<int> prWithdrawalId)
        {
            var prWithdrawalIdParameter = prWithdrawalId.HasValue ?
                new ObjectParameter("prWithdrawalId", prWithdrawalId) :
                new ObjectParameter("prWithdrawalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentDetails_Result>("GetPaymentDetails", prWithdrawalIdParameter);
        }
    
        public virtual int UpdateCompletedAppCommission(Nullable<int> prAppId, string prAgentLogin, string prCreatedBy)
        {
            var prAppIdParameter = prAppId.HasValue ?
                new ObjectParameter("prAppId", prAppId) :
                new ObjectParameter("prAppId", typeof(int));
    
            var prAgentLoginParameter = prAgentLogin != null ?
                new ObjectParameter("prAgentLogin", prAgentLogin) :
                new ObjectParameter("prAgentLogin", typeof(string));
    
            var prCreatedByParameter = prCreatedBy != null ?
                new ObjectParameter("prCreatedBy", prCreatedBy) :
                new ObjectParameter("prCreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCompletedAppCommission", prAppIdParameter, prAgentLoginParameter, prCreatedByParameter);
        }
    
        public virtual ObjectResult<FindClaimedApplication_Result> FindClaimedApplication(string prSearchKeyword)
        {
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindClaimedApplication_Result>("FindClaimedApplication", prSearchKeywordParameter);
        }
    
        public virtual ObjectResult<GetClawback_Result> GetClawback(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, Nullable<bool> prIsDeducted, Nullable<int> prAgentId, Nullable<bool> prIsAdmin, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prIsDeductedParameter = prIsDeducted.HasValue ?
                new ObjectParameter("prIsDeducted", prIsDeducted) :
                new ObjectParameter("prIsDeducted", typeof(bool));
    
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClawback_Result>("GetClawback", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prIsDeductedParameter, prAgentIdParameter, prIsAdminParameter, oTotalRecord);
        }
    
        public virtual int UpdateClaimableCommission(Nullable<int> prWithdrawalId)
        {
            var prWithdrawalIdParameter = prWithdrawalId.HasValue ?
                new ObjectParameter("prWithdrawalId", prWithdrawalId) :
                new ObjectParameter("prWithdrawalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateClaimableCommission", prWithdrawalIdParameter);
        }
    
        public virtual ObjectResult<GetIncentivesReceived_Result> GetIncentivesReceived(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, Nullable<int> prProduct, Nullable<int> prProductCategory, Nullable<int> prProductPackage, string prKeyword, Nullable<System.DateTime> prReceivedFrom, Nullable<System.DateTime> prReceivedUntil, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prProductParameter = prProduct.HasValue ?
                new ObjectParameter("prProduct", prProduct) :
                new ObjectParameter("prProduct", typeof(int));
    
            var prProductCategoryParameter = prProductCategory.HasValue ?
                new ObjectParameter("prProductCategory", prProductCategory) :
                new ObjectParameter("prProductCategory", typeof(int));
    
            var prProductPackageParameter = prProductPackage.HasValue ?
                new ObjectParameter("prProductPackage", prProductPackage) :
                new ObjectParameter("prProductPackage", typeof(int));
    
            var prKeywordParameter = prKeyword != null ?
                new ObjectParameter("prKeyword", prKeyword) :
                new ObjectParameter("prKeyword", typeof(string));
    
            var prReceivedFromParameter = prReceivedFrom.HasValue ?
                new ObjectParameter("prReceivedFrom", prReceivedFrom) :
                new ObjectParameter("prReceivedFrom", typeof(System.DateTime));
    
            var prReceivedUntilParameter = prReceivedUntil.HasValue ?
                new ObjectParameter("prReceivedUntil", prReceivedUntil) :
                new ObjectParameter("prReceivedUntil", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIncentivesReceived_Result>("GetIncentivesReceived", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prProductParameter, prProductCategoryParameter, prProductPackageParameter, prKeywordParameter, prReceivedFromParameter, prReceivedUntilParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<FindCompletedApplication_Result> FindCompletedApplication(string prSearchKeyword)
        {
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindCompletedApplication_Result>("FindCompletedApplication", prSearchKeywordParameter);
        }
    
        public virtual ObjectResult<GetIncentivesReceivedForDownload_Result> GetIncentivesReceivedForDownload(Nullable<int> prProduct, Nullable<int> prProductCategory, Nullable<int> prProductPackage, string prKeyword, Nullable<System.DateTime> prReceivedFrom, Nullable<System.DateTime> prReceivedUntil)
        {
            var prProductParameter = prProduct.HasValue ?
                new ObjectParameter("prProduct", prProduct) :
                new ObjectParameter("prProduct", typeof(int));
    
            var prProductCategoryParameter = prProductCategory.HasValue ?
                new ObjectParameter("prProductCategory", prProductCategory) :
                new ObjectParameter("prProductCategory", typeof(int));
    
            var prProductPackageParameter = prProductPackage.HasValue ?
                new ObjectParameter("prProductPackage", prProductPackage) :
                new ObjectParameter("prProductPackage", typeof(int));
    
            var prKeywordParameter = prKeyword != null ?
                new ObjectParameter("prKeyword", prKeyword) :
                new ObjectParameter("prKeyword", typeof(string));
    
            var prReceivedFromParameter = prReceivedFrom.HasValue ?
                new ObjectParameter("prReceivedFrom", prReceivedFrom) :
                new ObjectParameter("prReceivedFrom", typeof(System.DateTime));
    
            var prReceivedUntilParameter = prReceivedUntil.HasValue ?
                new ObjectParameter("prReceivedUntil", prReceivedUntil) :
                new ObjectParameter("prReceivedUntil", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIncentivesReceivedForDownload_Result>("GetIncentivesReceivedForDownload", prProductParameter, prProductCategoryParameter, prProductPackageParameter, prKeywordParameter, prReceivedFromParameter, prReceivedUntilParameter);
        }
    
        public virtual ObjectResult<GetAdminUsers_Result> GetAdminUsers(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdminUsers_Result>("GetAdminUsers", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<GetWithdrawalSubmittedForDownload_Result> GetWithdrawalSubmittedForDownload(string prStatus, string prAgent, Nullable<System.DateTime> prSubmittedFrom, Nullable<System.DateTime> prSubmittedTo, Nullable<System.DateTime> prCompletedFrom, Nullable<System.DateTime> prCompletedTo)
        {
            var prStatusParameter = prStatus != null ?
                new ObjectParameter("prStatus", prStatus) :
                new ObjectParameter("prStatus", typeof(string));
    
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            var prSubmittedFromParameter = prSubmittedFrom.HasValue ?
                new ObjectParameter("prSubmittedFrom", prSubmittedFrom) :
                new ObjectParameter("prSubmittedFrom", typeof(System.DateTime));
    
            var prSubmittedToParameter = prSubmittedTo.HasValue ?
                new ObjectParameter("prSubmittedTo", prSubmittedTo) :
                new ObjectParameter("prSubmittedTo", typeof(System.DateTime));
    
            var prCompletedFromParameter = prCompletedFrom.HasValue ?
                new ObjectParameter("prCompletedFrom", prCompletedFrom) :
                new ObjectParameter("prCompletedFrom", typeof(System.DateTime));
    
            var prCompletedToParameter = prCompletedTo.HasValue ?
                new ObjectParameter("prCompletedTo", prCompletedTo) :
                new ObjectParameter("prCompletedTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWithdrawalSubmittedForDownload_Result>("GetWithdrawalSubmittedForDownload", prStatusParameter, prAgentParameter, prSubmittedFromParameter, prSubmittedToParameter, prCompletedFromParameter, prCompletedToParameter);
        }
    
        public virtual ObjectResult<DboardMonthlyApplications_Result> DboardMonthlyApplications(Nullable<int> prSuperiorId)
        {
            var prSuperiorIdParameter = prSuperiorId.HasValue ?
                new ObjectParameter("prSuperiorId", prSuperiorId) :
                new ObjectParameter("prSuperiorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DboardMonthlyApplications_Result>("DboardMonthlyApplications", prSuperiorIdParameter);
        }
    
        public virtual ObjectResult<DboardTopSalesPackage_Result> DboardTopSalesPackage(Nullable<int> prAgentId, string prAgentName)
        {
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            var prAgentNameParameter = prAgentName != null ?
                new ObjectParameter("prAgentName", prAgentName) :
                new ObjectParameter("prAgentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DboardTopSalesPackage_Result>("DboardTopSalesPackage", prAgentIdParameter, prAgentNameParameter);
        }
    
        public virtual ObjectResult<DboardTotalSalesAndCommission_Result> DboardTotalSalesAndCommission(Nullable<int> prAgentId, string prAgentName)
        {
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            var prAgentNameParameter = prAgentName != null ?
                new ObjectParameter("prAgentName", prAgentName) :
                new ObjectParameter("prAgentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DboardTotalSalesAndCommission_Result>("DboardTotalSalesAndCommission", prAgentIdParameter, prAgentNameParameter);
        }
    
        public virtual ObjectResult<GetLoginBanners_Result> GetLoginBanners(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLoginBanners_Result>("GetLoginBanners", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, oTotalRecord);
        }
    
        public virtual ObjectResult<SelectItem> GetMyAgentsForCommissionSetting(Nullable<int> prSuperiorId, Nullable<int> prProductID, ObjectParameter oAllowCommConfig)
        {
            var prSuperiorIdParameter = prSuperiorId.HasValue ?
                new ObjectParameter("prSuperiorId", prSuperiorId) :
                new ObjectParameter("prSuperiorId", typeof(int));
    
            var prProductIDParameter = prProductID.HasValue ?
                new ObjectParameter("prProductID", prProductID) :
                new ObjectParameter("prProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectItem>("GetMyAgentsForCommissionSetting", prSuperiorIdParameter, prProductIDParameter, oAllowCommConfig);
        }
    
        public virtual ObjectResult<GetMyEntireTeam_Result> GetMyEntireTeam(Nullable<int> prSuperiorId)
        {
            var prSuperiorIdParameter = prSuperiorId.HasValue ?
                new ObjectParameter("prSuperiorId", prSuperiorId) :
                new ObjectParameter("prSuperiorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMyEntireTeam_Result>("GetMyEntireTeam", prSuperiorIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetUnreadMessagesCount(Nullable<int> prAppId, Nullable<bool> prIsAdmin)
        {
            var prAppIdParameter = prAppId.HasValue ?
                new ObjectParameter("prAppId", prAppId) :
                new ObjectParameter("prAppId", typeof(int));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUnreadMessagesCount", prAppIdParameter, prIsAdminParameter);
        }
    
        public virtual ObjectResult<GetApplicationDetails_Result> GetApplicationDetails(Nullable<int> prAppId, Nullable<bool> prIsAdmin)
        {
            var prAppIdParameter = prAppId.HasValue ?
                new ObjectParameter("prAppId", prAppId) :
                new ObjectParameter("prAppId", typeof(int));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApplicationDetails_Result>("GetApplicationDetails", prAppIdParameter, prIsAdminParameter);
        }
    
        public virtual ObjectResult<GetCustomerApplicationForDownload_Result> GetCustomerApplicationForDownload(Nullable<int> prProduct, Nullable<int> prProductCategory, Nullable<int> prProductPackage, Nullable<int> prStatus, string prAgent, Nullable<System.DateTime> prSubmittedFrom, Nullable<System.DateTime> prSubmittedTo, Nullable<System.DateTime> prActivatedFrom, Nullable<System.DateTime> prActivatedTo, string prResidentialType, string prKeyword, Nullable<bool> prDocumentCompleted, Nullable<bool> prIsAdmin, Nullable<int> prAgentId)
        {
            var prProductParameter = prProduct.HasValue ?
                new ObjectParameter("prProduct", prProduct) :
                new ObjectParameter("prProduct", typeof(int));
    
            var prProductCategoryParameter = prProductCategory.HasValue ?
                new ObjectParameter("prProductCategory", prProductCategory) :
                new ObjectParameter("prProductCategory", typeof(int));
    
            var prProductPackageParameter = prProductPackage.HasValue ?
                new ObjectParameter("prProductPackage", prProductPackage) :
                new ObjectParameter("prProductPackage", typeof(int));
    
            var prStatusParameter = prStatus.HasValue ?
                new ObjectParameter("prStatus", prStatus) :
                new ObjectParameter("prStatus", typeof(int));
    
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            var prSubmittedFromParameter = prSubmittedFrom.HasValue ?
                new ObjectParameter("prSubmittedFrom", prSubmittedFrom) :
                new ObjectParameter("prSubmittedFrom", typeof(System.DateTime));
    
            var prSubmittedToParameter = prSubmittedTo.HasValue ?
                new ObjectParameter("prSubmittedTo", prSubmittedTo) :
                new ObjectParameter("prSubmittedTo", typeof(System.DateTime));
    
            var prActivatedFromParameter = prActivatedFrom.HasValue ?
                new ObjectParameter("prActivatedFrom", prActivatedFrom) :
                new ObjectParameter("prActivatedFrom", typeof(System.DateTime));
    
            var prActivatedToParameter = prActivatedTo.HasValue ?
                new ObjectParameter("prActivatedTo", prActivatedTo) :
                new ObjectParameter("prActivatedTo", typeof(System.DateTime));
    
            var prResidentialTypeParameter = prResidentialType != null ?
                new ObjectParameter("prResidentialType", prResidentialType) :
                new ObjectParameter("prResidentialType", typeof(string));
    
            var prKeywordParameter = prKeyword != null ?
                new ObjectParameter("prKeyword", prKeyword) :
                new ObjectParameter("prKeyword", typeof(string));
    
            var prDocumentCompletedParameter = prDocumentCompleted.HasValue ?
                new ObjectParameter("prDocumentCompleted", prDocumentCompleted) :
                new ObjectParameter("prDocumentCompleted", typeof(bool));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerApplicationForDownload_Result>("GetCustomerApplicationForDownload", prProductParameter, prProductCategoryParameter, prProductPackageParameter, prStatusParameter, prAgentParameter, prSubmittedFromParameter, prSubmittedToParameter, prActivatedFromParameter, prActivatedToParameter, prResidentialTypeParameter, prKeywordParameter, prDocumentCompletedParameter, prIsAdminParameter, prAgentIdParameter);
        }
    
        public virtual ObjectResult<GetCompletedCustomerApplication_Result> GetCompletedCustomerApplication(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, Nullable<int> prProduct, Nullable<int> prProductCategory, Nullable<int> prProductPackage, string prCommStatus, string prViewAgent, Nullable<System.DateTime> prActivatedFrom, Nullable<System.DateTime> prActivatedTo, Nullable<System.DateTime> prPayDateFrom, Nullable<System.DateTime> prPayDateTo, string prKeyword, Nullable<bool> prDocumentCompleted, Nullable<bool> prIsAdmin, Nullable<int> prAgentId, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prProductParameter = prProduct.HasValue ?
                new ObjectParameter("prProduct", prProduct) :
                new ObjectParameter("prProduct", typeof(int));
    
            var prProductCategoryParameter = prProductCategory.HasValue ?
                new ObjectParameter("prProductCategory", prProductCategory) :
                new ObjectParameter("prProductCategory", typeof(int));
    
            var prProductPackageParameter = prProductPackage.HasValue ?
                new ObjectParameter("prProductPackage", prProductPackage) :
                new ObjectParameter("prProductPackage", typeof(int));
    
            var prCommStatusParameter = prCommStatus != null ?
                new ObjectParameter("prCommStatus", prCommStatus) :
                new ObjectParameter("prCommStatus", typeof(string));
    
            var prViewAgentParameter = prViewAgent != null ?
                new ObjectParameter("prViewAgent", prViewAgent) :
                new ObjectParameter("prViewAgent", typeof(string));
    
            var prActivatedFromParameter = prActivatedFrom.HasValue ?
                new ObjectParameter("prActivatedFrom", prActivatedFrom) :
                new ObjectParameter("prActivatedFrom", typeof(System.DateTime));
    
            var prActivatedToParameter = prActivatedTo.HasValue ?
                new ObjectParameter("prActivatedTo", prActivatedTo) :
                new ObjectParameter("prActivatedTo", typeof(System.DateTime));
    
            var prPayDateFromParameter = prPayDateFrom.HasValue ?
                new ObjectParameter("prPayDateFrom", prPayDateFrom) :
                new ObjectParameter("prPayDateFrom", typeof(System.DateTime));
    
            var prPayDateToParameter = prPayDateTo.HasValue ?
                new ObjectParameter("prPayDateTo", prPayDateTo) :
                new ObjectParameter("prPayDateTo", typeof(System.DateTime));
    
            var prKeywordParameter = prKeyword != null ?
                new ObjectParameter("prKeyword", prKeyword) :
                new ObjectParameter("prKeyword", typeof(string));
    
            var prDocumentCompletedParameter = prDocumentCompleted.HasValue ?
                new ObjectParameter("prDocumentCompleted", prDocumentCompleted) :
                new ObjectParameter("prDocumentCompleted", typeof(bool));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompletedCustomerApplication_Result>("GetCompletedCustomerApplication", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prProductParameter, prProductCategoryParameter, prProductPackageParameter, prCommStatusParameter, prViewAgentParameter, prActivatedFromParameter, prActivatedToParameter, prPayDateFromParameter, prPayDateToParameter, prKeywordParameter, prDocumentCompletedParameter, prIsAdminParameter, prAgentIdParameter, oTotalRecord);
        }
    
        public virtual int UpdateMyPasswordAdmin(string prAdminLogin, string prOldPassword, string prNewPassword, ObjectParameter oValidUpdate)
        {
            var prAdminLoginParameter = prAdminLogin != null ?
                new ObjectParameter("prAdminLogin", prAdminLogin) :
                new ObjectParameter("prAdminLogin", typeof(string));
    
            var prOldPasswordParameter = prOldPassword != null ?
                new ObjectParameter("prOldPassword", prOldPassword) :
                new ObjectParameter("prOldPassword", typeof(string));
    
            var prNewPasswordParameter = prNewPassword != null ?
                new ObjectParameter("prNewPassword", prNewPassword) :
                new ObjectParameter("prNewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMyPasswordAdmin", prAdminLoginParameter, prOldPasswordParameter, prNewPasswordParameter, oValidUpdate);
        }
    
        public virtual int UpdateMyPasswordAgent(Nullable<int> prAgentId, string prOldPassword, string prNewPassword, ObjectParameter oValidUpdate)
        {
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            var prOldPasswordParameter = prOldPassword != null ?
                new ObjectParameter("prOldPassword", prOldPassword) :
                new ObjectParameter("prOldPassword", typeof(string));
    
            var prNewPasswordParameter = prNewPassword != null ?
                new ObjectParameter("prNewPassword", prNewPassword) :
                new ObjectParameter("prNewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMyPasswordAgent", prAgentIdParameter, prOldPasswordParameter, prNewPasswordParameter, oValidUpdate);
        }
    
        public virtual int UpdateMessagesToRead(Nullable<int> prAppId, Nullable<bool> prIsAdmin)
        {
            var prAppIdParameter = prAppId.HasValue ?
                new ObjectParameter("prAppId", prAppId) :
                new ObjectParameter("prAppId", typeof(int));
    
            var prIsAdminParameter = prIsAdmin.HasValue ?
                new ObjectParameter("prIsAdmin", prIsAdmin) :
                new ObjectParameter("prIsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMessagesToRead", prAppIdParameter, prIsAdminParameter);
        }
    
        public virtual int GenerateActivationCode(Nullable<int> prRegistrationId, ObjectParameter oActivationCode)
        {
            var prRegistrationIdParameter = prRegistrationId.HasValue ?
                new ObjectParameter("prRegistrationId", prRegistrationId) :
                new ObjectParameter("prRegistrationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateActivationCode", prRegistrationIdParameter, oActivationCode);
        }
    
        public virtual ObjectResult<HasCommissionSet_Result> HasCommissionSet(Nullable<int> prCategoryId, string prAgent)
        {
            var prCategoryIdParameter = prCategoryId.HasValue ?
                new ObjectParameter("prCategoryId", prCategoryId) :
                new ObjectParameter("prCategoryId", typeof(int));
    
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HasCommissionSet_Result>("HasCommissionSet", prCategoryIdParameter, prAgentParameter);
        }
    
        public virtual ObjectResult<GetAppWithoutCommAssigned_Result> GetAppWithoutCommAssigned(Nullable<int> prAgentId)
        {
            var prAgentIdParameter = prAgentId.HasValue ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAppWithoutCommAssigned_Result>("GetAppWithoutCommAssigned", prAgentIdParameter);
        }
    
        public virtual ObjectResult<GetAgentsForDownload_Result> GetAgentsForDownload()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentsForDownload_Result>("GetAgentsForDownload");
        }
    
        public virtual ObjectResult<GetCompletedCustAppForDownload_Result> GetCompletedCustAppForDownload(Nullable<int> prProduct, Nullable<int> prProductCategory, Nullable<int> prProductPackage, string prCommStatus, string prViewAgent, Nullable<System.DateTime> prActivatedFrom, Nullable<System.DateTime> prActivatedTo, Nullable<System.DateTime> prPayDateFrom, Nullable<System.DateTime> prPayDateTo, string prKeyword, Nullable<bool> prDocumentCompleted)
        {
            var prProductParameter = prProduct.HasValue ?
                new ObjectParameter("prProduct", prProduct) :
                new ObjectParameter("prProduct", typeof(int));
    
            var prProductCategoryParameter = prProductCategory.HasValue ?
                new ObjectParameter("prProductCategory", prProductCategory) :
                new ObjectParameter("prProductCategory", typeof(int));
    
            var prProductPackageParameter = prProductPackage.HasValue ?
                new ObjectParameter("prProductPackage", prProductPackage) :
                new ObjectParameter("prProductPackage", typeof(int));
    
            var prCommStatusParameter = prCommStatus != null ?
                new ObjectParameter("prCommStatus", prCommStatus) :
                new ObjectParameter("prCommStatus", typeof(string));
    
            var prViewAgentParameter = prViewAgent != null ?
                new ObjectParameter("prViewAgent", prViewAgent) :
                new ObjectParameter("prViewAgent", typeof(string));
    
            var prActivatedFromParameter = prActivatedFrom.HasValue ?
                new ObjectParameter("prActivatedFrom", prActivatedFrom) :
                new ObjectParameter("prActivatedFrom", typeof(System.DateTime));
    
            var prActivatedToParameter = prActivatedTo.HasValue ?
                new ObjectParameter("prActivatedTo", prActivatedTo) :
                new ObjectParameter("prActivatedTo", typeof(System.DateTime));
    
            var prPayDateFromParameter = prPayDateFrom.HasValue ?
                new ObjectParameter("prPayDateFrom", prPayDateFrom) :
                new ObjectParameter("prPayDateFrom", typeof(System.DateTime));
    
            var prPayDateToParameter = prPayDateTo.HasValue ?
                new ObjectParameter("prPayDateTo", prPayDateTo) :
                new ObjectParameter("prPayDateTo", typeof(System.DateTime));
    
            var prKeywordParameter = prKeyword != null ?
                new ObjectParameter("prKeyword", prKeyword) :
                new ObjectParameter("prKeyword", typeof(string));
    
            var prDocumentCompletedParameter = prDocumentCompleted.HasValue ?
                new ObjectParameter("prDocumentCompleted", prDocumentCompleted) :
                new ObjectParameter("prDocumentCompleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompletedCustAppForDownload_Result>("GetCompletedCustAppForDownload", prProductParameter, prProductCategoryParameter, prProductPackageParameter, prCommStatusParameter, prViewAgentParameter, prActivatedFromParameter, prActivatedToParameter, prPayDateFromParameter, prPayDateToParameter, prKeywordParameter, prDocumentCompletedParameter);
        }
    
        public virtual ObjectResult<ResetAgentPassword_Result> ResetAgentPassword(string prAgentId, string prNewPassword, string prUpdatedBy)
        {
            var prAgentIdParameter = prAgentId != null ?
                new ObjectParameter("prAgentId", prAgentId) :
                new ObjectParameter("prAgentId", typeof(string));
    
            var prNewPasswordParameter = prNewPassword != null ?
                new ObjectParameter("prNewPassword", prNewPassword) :
                new ObjectParameter("prNewPassword", typeof(string));
    
            var prUpdatedByParameter = prUpdatedBy != null ?
                new ObjectParameter("prUpdatedBy", prUpdatedBy) :
                new ObjectParameter("prUpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResetAgentPassword_Result>("ResetAgentPassword", prAgentIdParameter, prNewPasswordParameter, prUpdatedByParameter);
        }
    
        public virtual int GetAdminEmail(ObjectParameter oEmails)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAdminEmail", oEmails);
        }
    
        public virtual ObjectResult<GetAgentPocket_Result> GetAgentPocket(Nullable<int> prCurrentPage, Nullable<int> prPageSize, string prSortColumn, Nullable<bool> prSortInAsc, string prSearchKeyword, string prFlowType, Nullable<bool> prRecordStatus, ObjectParameter oTotalRecord)
        {
            var prCurrentPageParameter = prCurrentPage.HasValue ?
                new ObjectParameter("prCurrentPage", prCurrentPage) :
                new ObjectParameter("prCurrentPage", typeof(int));
    
            var prPageSizeParameter = prPageSize.HasValue ?
                new ObjectParameter("prPageSize", prPageSize) :
                new ObjectParameter("prPageSize", typeof(int));
    
            var prSortColumnParameter = prSortColumn != null ?
                new ObjectParameter("prSortColumn", prSortColumn) :
                new ObjectParameter("prSortColumn", typeof(string));
    
            var prSortInAscParameter = prSortInAsc.HasValue ?
                new ObjectParameter("prSortInAsc", prSortInAsc) :
                new ObjectParameter("prSortInAsc", typeof(bool));
    
            var prSearchKeywordParameter = prSearchKeyword != null ?
                new ObjectParameter("prSearchKeyword", prSearchKeyword) :
                new ObjectParameter("prSearchKeyword", typeof(string));
    
            var prFlowTypeParameter = prFlowType != null ?
                new ObjectParameter("prFlowType", prFlowType) :
                new ObjectParameter("prFlowType", typeof(string));
    
            var prRecordStatusParameter = prRecordStatus.HasValue ?
                new ObjectParameter("prRecordStatus", prRecordStatus) :
                new ObjectParameter("prRecordStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgentPocket_Result>("GetAgentPocket", prCurrentPageParameter, prPageSizeParameter, prSortColumnParameter, prSortInAscParameter, prSearchKeywordParameter, prFlowTypeParameter, prRecordStatusParameter, oTotalRecord);
        }
    
        public virtual int UpdateAgentPocket(string prAgent, Nullable<int> prWithdrawalId)
        {
            var prAgentParameter = prAgent != null ?
                new ObjectParameter("prAgent", prAgent) :
                new ObjectParameter("prAgent", typeof(string));
    
            var prWithdrawalIdParameter = prWithdrawalId.HasValue ?
                new ObjectParameter("prWithdrawalId", prWithdrawalId) :
                new ObjectParameter("prWithdrawalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAgentPocket", prAgentParameter, prWithdrawalIdParameter);
        }
    
        public virtual int TerminateWithdrawal(Nullable<int> prWithdrawalId, string prModifiedBy)
        {
            var prWithdrawalIdParameter = prWithdrawalId.HasValue ?
                new ObjectParameter("prWithdrawalId", prWithdrawalId) :
                new ObjectParameter("prWithdrawalId", typeof(int));
    
            var prModifiedByParameter = prModifiedBy != null ?
                new ObjectParameter("prModifiedBy", prModifiedBy) :
                new ObjectParameter("prModifiedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TerminateWithdrawal", prWithdrawalIdParameter, prModifiedByParameter);
        }
    }
}
