//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    
    public partial class CommissionSettings
    {
        public Nullable<int> CategoryId { get; set; }
        public string Category { get; set; }
        public Nullable<short> SupCommission { get; set; }
        public Nullable<short> AgentCommissionPer { get; set; }
    }
}
