//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocument
    {
        public int DocId { get; set; }
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Size { get; set; }
    
        public virtual CustomerApplication CustomerApplication { get; set; }
    }
}
