//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTrail
    {
        public int Id { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string LoginName { get; set; }
        public System.DateTime LoginDate { get; set; }
    }
}
