//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.RegistrationDocuments = new HashSet<RegistrationDocument>();
        }
    
        public int RegId { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Nric { get; set; }
        public string CompanyName { get; set; }
        public string CompanyRegNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string MobileNo { get; set; }
        public string TelNo { get; set; }
        public string UserLogin { get; set; }
        public byte[] PasswordHash { get; set; }
        public Nullable<int> SuperiorId { get; set; }
        public string BankName { get; set; }
        public string BankAccNo { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationDocument> RegistrationDocuments { get; set; }
    }
}
