//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    
    public partial class SelectItem
    {
        public int DisplayValue { get; set; }
        public string DisplayText { get; set; }
        public Nullable<bool> Selected { get; set; }
    }
}
