//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawalItem
    {
        public int WithdrawalItemId { get; set; }
        public Nullable<int> WithdrawalId { get; set; }
        public Nullable<int> ClaimCommId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string TransactionDetails { get; set; }
        public string PackageName { get; set; }
        public Nullable<decimal> PackageComm { get; set; }
        public Nullable<short> AgentComm { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> DeductAmount { get; set; }
        public string TransactionType { get; set; }
        public string TransactionDate { get; set; }
    
        public virtual Withdrawal Withdrawal { get; set; }
    }
}
