//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadbandZone_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Withdrawal()
        {
            this.AgentPockets = new HashSet<AgentPocket>();
            this.ClaimableCommissions = new HashSet<ClaimableCommission>();
            this.ClaimableCommissions1 = new HashSet<ClaimableCommission>();
            this.WithdrawalItems = new HashSet<WithdrawalItem>();
        }
    
        public int WithdrawalId { get; set; }
        public string Agent { get; set; }
        public Nullable<decimal> WithdrawAmount { get; set; }
        public Nullable<decimal> Claimed { get; set; }
        public Nullable<decimal> Incentives { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public string ReferenceNo { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string CompletedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPocket> AgentPockets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimableCommission> ClaimableCommissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimableCommission> ClaimableCommissions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawalItem> WithdrawalItems { get; set; }
    }
}
